### ISSUE TITLE
这个你能用吗?我点击图片不能预览

### ISSUE THREAD

**Issue by lxk0301** [laii7/vue-imageViewer#1]
man.js引入
![image](https://user-images.githubusercontent.com/21308593/48886267-4bc3d400-ee66-11e8-9734-61fe41b9714e.png)
具体页面使用
![image](https://user-images.githubusercontent.com/21308593/48886277-5c744a00-ee66-11e8-9929-44b00319aaa1.png)
然后点击图片不能预览

**Comment by laii7** [comment]
可以呀，你是不是引用路径出错了，可以加我QQ535654314，我帮你看看

**Comment by laii7** [comment]
可以呀，你这个@click="$imageViewer"，可以加我qq535654314，我帮你看看

**Comment by lxk0301** [comment]
> 可以的，我把这个封装成项目中用的通用组件了，用起来非常方便。

嗯 ,,我现在也 解决了  可以使用 ,之前是因为在,methods:里面 添加了和组件点击事件一样的方法名字

**Comment by jiayoujyjyjy** [comment]
为啥不能用呢？大佬，我在具体页面上用提示 $imageViewer is not defined

**Comment by laii7** [comment]
> 为啥不能用呢？大佬，我在具体页面上用提示 $imageViewer is not defined
截图看看你怎么用的
